
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/tony/Downloads/Tkinter-Designer-master 2/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("828x510")
window.configure(bg = "#B2D2A4")


canvas = Canvas(
    window,
    bg = "#B2D2A4",
    height = 510,
    width = 828,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    828.0,
    72.0,
    fill="#F6A21E",
    outline="")

canvas.create_text(
    2.0,
    1.0,
    anchor="nw",
    text="Portfolio Generator",
    fill="#104210",
    font=("AnonymousPro Regular", 38 * -1)
)

canvas.create_text(
    334.0,
    226.0,
    anchor="nw",
    text="Enter Risk ",
    fill="#000000",
    font=("AnonymousPro Regular", 30 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    430.5,
    273.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=344.0,
    y=255.0,
    width=173.0,
    height=34.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=334.0,
    y=305.0,
    width=193.0,
    height=36.0
)
window.resizable(False, False)
window.mainloop()
