
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import yfinance as yf
import pandas as pd
import warnings
import numpy as np

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/tony/Downloads/Tkinter-Designer-master 2/build/assets/frame0")


warnings.filterwarnings("ignore")
pd.options.display.float_format = '{:.4%}'.format

# Date range
start = '2016-01-01'
end = '2019-12-30'

# Tickers of assets
assets = ['JCI', 'TGT', 'CMCSA', 'CPB', 'MO', 'APA', 'MMC', 'JPM',
          'ZION', 'PSA', 'BAX', 'BMY', 'LUV', 'PCAR', 'TXT', 'TMO',
          'DE', 'MSFT', 'HPQ', 'SEE', 'VZ', 'CNP', 'NI', 'T', 'BA']
assets.sort()

# Downloading data
data = yf.download(assets, start = start, end = end)
data = data.loc[:,('Adj Close', slice(None))]
data.columns = assets

Y = data[assets].pct_change().dropna()





gotText = ""




def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def clear_text():
    gotText = entry_2.get()
    entry_1.delete(0, 'end')
    entry_2.delete(0, 'end')
    if isFound():
        return
    else:
        print(Y.head())
        stocks.append(gotText)

    for i in stocks:
        print(i)

def isFound():
    for x in stocks:
        if gotText == x:
            return True
    return False


stocks = ["TEMP1", "TEMP2", "TEMP3", "TEMP4"]


window = Tk()

window.geometry("828x510")
window.configure(bg = "#B2D2A4")


canvas = Canvas(
    window,
    bg = "#B2D2A4",
    height = 510,
    width = 828,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    828.0,
    72.0,
    fill="#F6A21E",
    outline="")

canvas.create_text(
    266,
    1.0,
    anchor="nw",
    text="Portfolio Generator",
    fill="#104210",
    font=("AnonymousPro Regular", 38 * -1)
)

canvas.create_text(
    325.0,
    255.0,
    anchor="nw",
    text="Add A Stock",
    fill="#000000",
    font=("AnonymousPro Regular", 30 * -1)
)
canvas.create_text(
    265.0,
    430.0,
    anchor="nw",
    text="Use Stock's Tick Symbol",
    fill="#000000",
    font=("AnonymousPro Regular", 30 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    421.5,
    202.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=335.0,
    y=184.0,
    width=173.0,
    height=34.0
)

canvas.create_text(
    325.0,
    137.0,
    anchor="nw",
    text="Enter Risk ",
    fill="#000000",
    font=("AnonymousPro Regular", 30 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    421.5,
    308.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=335.0,
    y=290.0,
    width=173.0,
    height=34.0
)


button_1 = Button(
    text="Generate Portfolio", font='AnonymousPro',
    borderwidth=0,
    highlightthickness=0,
    command=lambda: clear_text(),
    relief="flat"
)
button_1.place(
    x=325.0,
    y=369.0,
    width=193.0,
    height=36.0
)


window.resizable(False, False)
window.mainloop()
